# Generated by Django 3.1.7 on 2021-06-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='eng',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sci',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
